INSERT INTO oseba (ime, priimek) VALUES ('Ana', 'Banana');
INSERT INTO oseba (ime, priimek) VALUES ('Jaka', 'Novak');
INSERT INTO oseba (ime, priimek) VALUES ('Tine', 'Mraz');
INSERT INTO oseba (ime, priimek) VALUES ('Anja', 'Zver  ');
INSERT INTO soba (ime_sobe, velikost, st_ljudi, max_ljudi, osebe_sobe, opis, kljucna_beseda) VALUES ('Kipi', 123, 21, 21, 1, 'Izjemni kipi iz 13. stol.', 'statue');
INSERT INTO soba (ime_sobe, velikost, st_ljudi, max_ljudi, osebe_sobe, opis, kljucna_beseda) VALUES ('Slike Van Gogh', 13, 42, 312, 1, 'Izjemne slike Vincenta.', 'painter');
INSERT INTO soba (ime_sobe, velikost, st_ljudi, max_ljudi, osebe_sobe, opis, kljucna_beseda) VALUES ('Krizarske vojne', 15, 12, 12, 2, 'Najdbe iz Jeruzalema.', 'artefacts');
INSERT INTO soba (ime_sobe, velikost, st_ljudi, max_ljudi, osebe_sobe, opis, kljucna_beseda) VALUES ('Razstava slik', 82, 2, 32, 3, 'Najdbe slik iz renesanse.', 'painting');
INSERT INTO soba (ime_sobe, velikost, st_ljudi, max_ljudi, osebe_sobe, opis, kljucna_beseda) VALUES ('Cakalnica', 22, 10, 77, 3, 'Kraj za postanek.', 'waiting');
INSERT INTO soba (ime_sobe, velikost, st_ljudi, max_ljudi, osebe_sobe, opis, kljucna_beseda) VALUES ('Cakalnica', 22, 10, 77, 1, 'Kraj za postanek.','waiting');
INSERT INTO soba (ime_sobe, velikost, st_ljudi, max_ljudi, osebe_sobe, opis, kljucna_beseda) VALUES ('Razstava albumov', 82, 2, 32, 3, 'Albumi za vse.', 'album');
INSERT INTO soba (ime_sobe, velikost, st_ljudi, max_ljudi, osebe_sobe, opis, kljucna_beseda) VALUES ('Skice', 82, 2, 32, 3, 'Izjemne skice.', 'sketch');
INSERT INTO soba (ime_sobe, velikost, st_ljudi, max_ljudi, osebe_sobe, opis, kljucna_beseda) VALUES ('Igrisce', 82, 2, 32, 3, 'Nekaj za najmlajse.', 'playground');
INSERT INTO vrata (vrata_sobe) VALUES (1);
INSERT INTO vrata (vrata_sobe) VALUES (2);
INSERT INTO vrata (vrata_sobe) VALUES (2);