kumuluzee:
  name: simple-jdbc-sample
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/sledilnikDS
      connection-url: jdbc:postgresql://localhost:5432/uporabniki
      username: postgres
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: both
        jndi-name: jdbc/sledilnikDS
      http-health-check:
        - connection-url: http://localhost:8080/servlet
        - connection-url: http://localhost:8080/v1/sobe
        - connection-url: http://localhost:8081/servlet
        - connection-url: https://github.com/kumuluz/kumuluzee-health
  integrations:
    podatki:
      base-url: http://localhost:8081/V1podatki
    slike-api:
      base-url: https://api.unsplash.com
      api-key: zAUlUQA2fa4G53X-7-cdtVjOBpoOjNNOqx1acSWOlcM
  security:
    keycloak:
      json: '{
               "realm": "master",
               "auth-server-url": "http://localhost:8082/auth/",
               "ssl-required": "external",
               "resource": "sobe-app",
               "public-client": true,
               "confidential-port": 0
             }'